// glslangValidator -V tests/shaders/add.comp -o compiled_shaders/tests/add.spv
#version 460

// MSB [0 uint] - LSB [1 uint]
struct u64
{
	uint lsb;
	uint msb;
};

u64 add(u64 x, u64 y)
{
	uint lsb_sum = x.lsb + y.lsb;

	// We assume we will not face overflow
	uint msb_sum = x.msb + y.msb + uint(lsb_sum < y.lsb || lsb_sum < x.lsb);

	return u64(lsb_sum, msb_sum);
}

layout(binding = 0) buffer Input {
   u64 values[ ];
};

layout (local_size_x = 8, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform pushConstants {
	uint   buff_size;
    u64[2] key;
} metadata;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	if (index >= metadata.buff_size) return;

	values[index] = add(metadata.key[0], metadata.key[1]);
}